[build]
# Zielplattform für das Kompilieren angeben
# Hier wird explizit die MSVC-Version für Windows 64-bit verwendet

target = "x86_64-pc-windows-msvc"
target-dir = "./target"

#| Ziel                       | Beschreibung                      |
#| -------------------------- | --------------------------------- |
#| `x86_64-pc-windows-gnu`    | Windows mit MinGW (GNU Toolchain) |
#| `x86_64-unknown-linux-gnu` | Linux x64                         |
#| `x86_64-apple-darwin`      | macOS Intel                       |
#| `aarch64-pc-windows-msvc`  | Windows auf ARM64                 |
#| `wasm32-unknown-unknown`   | WebAssembly ohne Bindings         |
#| `wasm32-wasi`              | WebAssembly mit WASI              |
